version: 0.2

phases:
  install:
   runtime-versions:
   typescript: 16
    commands:
      - npm install -g aws-cdk
  build:
    commands:
      - cdk synth
  post-build:
    commands:
      - cdk deploy
