version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.00
    commands:
      - "npm install -g typescript"
      - "npm install -g aws-cdk"
  pre_build:
    commands:
      - cdk synth

  build:
    commands:
    - npm run build

  post_build:
    commands:
      - cdk deploy
