version: 0.2

phases:
  install:
    commands:
      - "nvm install 16"  
      - "nvm use 16"
      - "npm install -g typescript"
      - "npm install -g aws-cdk"
   
   pre_build:
     commands:
       - cdk synth

  build:
    commands:
    - npm run build

  post_build:
    commands:
      - cdk deploy
